// This file is auto-generated by @hey-api/openapi-ts

export const AuxiliarySourceJobPublicSchema = {
    properties: {
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        phase: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phase'
        },
        crawled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Crawled At'
        }
    },
    type: 'object',
    required: ['job_id', 'status'],
    title: 'AuxiliarySourceJobPublic'
} as const;

export const BilibiliAccessStatusPublicSchema = {
    properties: {
        metadata_cookie_configured: {
            type: 'boolean',
            title: 'Metadata Cookie Configured'
        },
        download_auth_configured: {
            type: 'boolean',
            title: 'Download Auth Configured'
        },
        has_database_override: {
            type: 'boolean',
            title: 'Has Database Override'
        },
        effective_cookie_source: {
            type: 'string',
            title: 'Effective Cookie Source'
        },
        cookie_header_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cookie Header Summary'
        },
        netscape_cookie_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Netscape Cookie Summary'
        },
        download_user_agent_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Download User Agent Summary'
        },
        download_user_agent_configured: {
            type: 'boolean',
            title: 'Download User Agent Configured'
        },
        yt_dlp_cookies_file_configured: {
            type: 'boolean',
            title: 'Yt Dlp Cookies File Configured'
        },
        yt_dlp_cookies_from_browser_configured: {
            type: 'boolean',
            title: 'Yt Dlp Cookies From Browser Configured'
        },
        yt_dlp_impersonate_configured: {
            type: 'boolean',
            title: 'Yt Dlp Impersonate Configured'
        },
        database_cookie_updated_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Database Cookie Updated By'
        },
        database_cookie_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Database Cookie Updated At'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        }
    },
    type: 'object',
    required: ['metadata_cookie_configured', 'download_auth_configured', 'has_database_override', 'effective_cookie_source', 'download_user_agent_configured', 'yt_dlp_cookies_file_configured', 'yt_dlp_cookies_from_browser_configured', 'yt_dlp_impersonate_configured'],
    title: 'BilibiliAccessStatusPublic'
} as const;

export const BilibiliAccessUpdateSchema = {
    properties: {
        netscape_cookies: {
            type: 'string',
            maxLength: 262144,
            minLength: 1,
            title: 'Netscape Cookies'
        },
        download_user_agent: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Download User Agent'
        }
    },
    type: 'object',
    required: ['netscape_cookies'],
    title: 'BilibiliAccessUpdate'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IngestJobDetailSchema = {
    properties: {
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        bvid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bvid'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        phase: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phase'
        },
        requested_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested By'
        },
        options: {
            additionalProperties: true,
            type: 'object',
            title: 'Options'
        },
        progress: {
            additionalProperties: true,
            type: 'object',
            title: 'Progress'
        },
        error: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/JobErrorPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: ['job_id', 'status', 'created_at'],
    title: 'IngestJobDetail'
} as const;

export const IngestJobPublicSchema = {
    properties: {
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        bvid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bvid'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        phase: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phase'
        }
    },
    type: 'object',
    required: ['job_id', 'status'],
    title: 'IngestJobPublic'
} as const;

export const IngestJobSummaryPublicSchema = {
    properties: {
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        bvid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bvid'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        phase: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phase'
        },
        requested_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested By'
        },
        error: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/JobErrorPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: ['job_id', 'status', 'created_at'],
    title: 'IngestJobSummaryPublic'
} as const;

export const IngestJobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IngestJobSummaryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            title: 'Offset'
        }
    },
    type: 'object',
    required: ['data', 'count', 'limit', 'offset'],
    title: 'IngestJobsPublic'
} as const;

export const IngestVideoOptionsSchema = {
    properties: {
        download_video: {
            type: 'boolean',
            title: 'Download Video',
            default: false
        },
        max_height: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 4320,
                    minimum: 144
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Height'
        },
        store_source_archive: {
            type: 'boolean',
            title: 'Store Source Archive',
            default: true
        },
        create_normalized_mp4: {
            type: 'boolean',
            title: 'Create Normalized Mp4',
            default: true
        },
        create_hls: {
            type: 'boolean',
            title: 'Create Hls',
            default: false
        },
        fetch_comments: {
            type: 'boolean',
            title: 'Fetch Comments',
            default: false
        },
        fetch_danmaku: {
            type: 'boolean',
            title: 'Fetch Danmaku',
            default: false
        },
        fetch_subtitles: {
            type: 'boolean',
            title: 'Fetch Subtitles',
            default: true
        },
        transcribe_subtitles: {
            type: 'boolean',
            title: 'Transcribe Subtitles',
            default: true
        },
        force_refresh: {
            type: 'boolean',
            title: 'Force Refresh',
            default: false
        }
    },
    type: 'object',
    title: 'IngestVideoOptions'
} as const;

export const IngestVideoRequestSchema = {
    properties: {
        input: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Input'
        },
        options: {
            '$ref': '#/components/schemas/IngestVideoOptions'
        }
    },
    type: 'object',
    required: ['input'],
    title: 'IngestVideoRequest'
} as const;

export const JobErrorPublicSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    title: 'JobErrorPublic'
} as const;

export const MediaAssetDetailPublicSchema = {
    properties: {
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id'
        },
        asset_type: {
            type: 'string',
            title: 'Asset Type'
        },
        variant: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variant'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        cid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cid'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Bytes'
        },
        sha256: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sha256'
        },
        container_format: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Container Format'
        },
        video_codec: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Codec'
        },
        audio_codec: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio Codec'
        },
        width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Width'
        },
        height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        ready_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ready At'
        },
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        s3_bucket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Bucket'
        },
        s3_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Key'
        }
    },
    type: 'object',
    required: ['asset_id', 'asset_type', 'status', 'created_at', 'bvid'],
    title: 'MediaAssetDetailPublic'
} as const;

export const MediaAssetDownloadDescriptorSchema = {
    properties: {
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id'
        },
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        s3_bucket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Bucket'
        },
        s3_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'S3 Key'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['asset_id', 'bvid', 'expires_at'],
    title: 'MediaAssetDownloadDescriptor'
} as const;

export const MediaAssetPublicSchema = {
    properties: {
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id'
        },
        asset_type: {
            type: 'string',
            title: 'Asset Type'
        },
        variant: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variant'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        cid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cid'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Bytes'
        },
        sha256: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sha256'
        },
        container_format: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Container Format'
        },
        video_codec: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Codec'
        },
        audio_codec: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio Codec'
        },
        width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Width'
        },
        height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        ready_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ready At'
        }
    },
    type: 'object',
    required: ['asset_id', 'asset_type', 'status', 'created_at'],
    title: 'MediaAssetPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SignedUrlRequestSchema = {
    properties: {
        expires_in: {
            type: 'integer',
            maximum: 86400,
            minimum: 60,
            title: 'Expires In',
            default: 900
        }
    },
    type: 'object',
    title: 'SignedUrlRequest'
} as const;

export const SignedUrlResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['url', 'expires_in'],
    title: 'SignedUrlResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VideoAssetsPublicSchema = {
    properties: {
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        assets: {
            items: {
                '$ref': '#/components/schemas/MediaAssetPublic'
            },
            type: 'array',
            title: 'Assets'
        }
    },
    type: 'object',
    required: ['bvid', 'assets'],
    title: 'VideoAssetsPublic'
} as const;

export const VideoCommentContextPublicSchema = {
    properties: {
        rpid: {
            type: 'integer',
            title: 'Rpid'
        },
        oid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Oid'
        },
        mid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mid'
        },
        uname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uname'
        },
        root: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Root'
        },
        parent: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        like_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Like Count'
        },
        reply_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reply Count'
        },
        ctime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ctime'
        }
    },
    type: 'object',
    required: ['rpid'],
    title: 'VideoCommentContextPublic'
} as const;

export const VideoCommentImageEntryPublicSchema = {
    properties: {
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Width'
        },
        height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        },
        asset_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Asset Id'
        },
        storage_status: {
            type: 'string',
            title: 'Storage Status'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        asset: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MediaAssetPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        image_id: {
            type: 'string',
            format: 'uuid',
            title: 'Image Id'
        },
        ordinal: {
            type: 'integer',
            title: 'Ordinal'
        },
        crawled_at: {
            type: 'string',
            format: 'date-time',
            title: 'Crawled At'
        },
        comment: {
            '$ref': '#/components/schemas/VideoCommentContextPublic'
        }
    },
    type: 'object',
    required: ['storage_status', 'image_id', 'ordinal', 'crawled_at', 'comment'],
    title: 'VideoCommentImageEntryPublic'
} as const;

export const VideoCommentImagePublicSchema = {
    properties: {
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Width'
        },
        height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        },
        asset_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Asset Id'
        },
        storage_status: {
            type: 'string',
            title: 'Storage Status'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        asset: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MediaAssetPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['storage_status'],
    title: 'VideoCommentImagePublic'
} as const;

export const VideoCommentImagesPublicSchema = {
    properties: {
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            title: 'Offset'
        },
        completeness: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoCommentsCompletenessPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        images: {
            items: {
                '$ref': '#/components/schemas/VideoCommentImageEntryPublic'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: ['bvid', 'count', 'limit', 'offset', 'images'],
    title: 'VideoCommentImagesPublic'
} as const;

export const VideoCommentPublicSchema = {
    properties: {
        rpid: {
            type: 'integer',
            title: 'Rpid'
        },
        oid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Oid'
        },
        mid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mid'
        },
        uname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uname'
        },
        root: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Root'
        },
        parent: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        like_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Like Count'
        },
        reply_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reply Count'
        },
        ctime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ctime'
        },
        images: {
            items: {
                '$ref': '#/components/schemas/VideoCommentImagePublic'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: ['rpid'],
    title: 'VideoCommentPublic'
} as const;

export const VideoCommentsCompletenessPublicSchema = {
    properties: {
        partial: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Partial'
        },
        expected_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Count'
        },
        fetched_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fetched Count'
        },
        stored_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stored Count'
        },
        fallback_used: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fallback Used'
        },
        image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Count'
        },
        stored_image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stored Image Count'
        },
        failed_image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed Image Count'
        },
        skipped_image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skipped Image Count'
        },
        source_job: {
            '$ref': '#/components/schemas/AuxiliarySourceJobPublic'
        }
    },
    type: 'object',
    required: ['source_job'],
    title: 'VideoCommentsCompletenessPublic'
} as const;

export const VideoCommentsPublicSchema = {
    properties: {
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        thread_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thread Count'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            title: 'Offset'
        },
        completeness: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoCommentsCompletenessPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        comments: {
            items: {
                '$ref': '#/components/schemas/VideoCommentPublic'
            },
            type: 'array',
            title: 'Comments'
        }
    },
    type: 'object',
    required: ['bvid', 'count', 'limit', 'offset', 'comments'],
    title: 'VideoCommentsPublic'
} as const;

export const VideoDanmakuCompletenessPublicSchema = {
    properties: {
        partial: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Partial'
        },
        stored_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stored Count'
        },
        duplicate_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duplicate Count'
        },
        cid_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cid Count'
        },
        filled_cid_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filled Cid Count'
        },
        crawl_source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Crawl Source'
        },
        history_used: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'History Used'
        },
        snapshot_used: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Snapshot Used'
        },
        indexed_month_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Indexed Month Count'
        },
        expected_days_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Days Count'
        },
        fetched_days_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fetched Days Count'
        },
        pages: {
            items: {
                '$ref': '#/components/schemas/VideoDanmakuPageCoveragePublic'
            },
            type: 'array',
            title: 'Pages'
        },
        source_job: {
            '$ref': '#/components/schemas/AuxiliarySourceJobPublic'
        }
    },
    type: 'object',
    required: ['source_job'],
    title: 'VideoDanmakuCompletenessPublic'
} as const;

export const VideoDanmakuEntriesPublicSchema = {
    properties: {
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            title: 'Offset'
        },
        completeness: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoDanmakuCompletenessPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        danmaku: {
            items: {
                '$ref': '#/components/schemas/VideoDanmakuEntryPublic'
            },
            type: 'array',
            title: 'Danmaku'
        }
    },
    type: 'object',
    required: ['bvid', 'count', 'limit', 'offset', 'danmaku'],
    title: 'VideoDanmakuEntriesPublic'
} as const;

export const VideoDanmakuEntryPublicSchema = {
    properties: {
        danmaku_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Danmaku Id'
        },
        cid: {
            type: 'integer',
            title: 'Cid'
        },
        time_offset_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Offset Seconds'
        },
        mode: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mode'
        },
        font_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Font Size'
        },
        color: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        sent_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sent At'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        history_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'History Date'
        }
    },
    type: 'object',
    required: ['cid', 'source'],
    title: 'VideoDanmakuEntryPublic'
} as const;

export const VideoDanmakuPageCoveragePublicSchema = {
    properties: {
        cid: {
            type: 'integer',
            title: 'Cid'
        },
        count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        history_used: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'History Used'
        },
        snapshot_used: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Snapshot Used'
        },
        indexed_month_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Indexed Month Count'
        },
        expected_days_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Days Count'
        },
        fetched_days_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fetched Days Count'
        },
        partial: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Partial'
        }
    },
    type: 'object',
    required: ['cid'],
    title: 'VideoDanmakuPageCoveragePublic'
} as const;

export const VideoDetailPublicSchema = {
    properties: {
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        aid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        owner_mid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Mid'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        pubdate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pubdate'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        cover_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Url'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        takedown_status: {
            type: 'string',
            title: 'Takedown Status'
        },
        last_crawled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Crawled At'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        stat: {
            additionalProperties: true,
            type: 'object',
            title: 'Stat'
        }
    },
    type: 'object',
    required: ['bvid', 'title', 'takedown_status'],
    title: 'VideoDetailPublic'
} as const;

export const VideoSubtitlePublicSchema = {
    properties: {
        subtitle_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subtitle Id'
        },
        cid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cid'
        },
        lang: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lang'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        asset_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Asset Id'
        },
        crawled_at: {
            type: 'string',
            format: 'date-time',
            title: 'Crawled At'
        }
    },
    type: 'object',
    required: ['subtitle_id', 'crawled_at'],
    title: 'VideoSubtitlePublic'
} as const;

export const VideoSubtitlesCompletenessPublicSchema = {
    properties: {
        partial: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Partial'
        },
        stored_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stored Count'
        },
        cid_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cid Count'
        },
        languages: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Languages'
        },
        source_job: {
            '$ref': '#/components/schemas/AuxiliarySourceJobPublic'
        }
    },
    type: 'object',
    required: ['source_job'],
    title: 'VideoSubtitlesCompletenessPublic'
} as const;

export const VideoSubtitlesPublicSchema = {
    properties: {
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            title: 'Offset'
        },
        completeness: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoSubtitlesCompletenessPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        subtitles: {
            items: {
                '$ref': '#/components/schemas/VideoSubtitlePublic'
            },
            type: 'array',
            title: 'Subtitles'
        }
    },
    type: 'object',
    required: ['bvid', 'count', 'limit', 'offset', 'subtitles'],
    title: 'VideoSubtitlesPublic'
} as const;

export const VideoSummaryPublicSchema = {
    properties: {
        bvid: {
            type: 'string',
            title: 'Bvid'
        },
        aid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        owner_mid: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Mid'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        pubdate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pubdate'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        cover_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Url'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        takedown_status: {
            type: 'string',
            title: 'Takedown Status'
        },
        last_crawled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Crawled At'
        }
    },
    type: 'object',
    required: ['bvid', 'title', 'takedown_status'],
    title: 'VideoSummaryPublic'
} as const;

export const VideosPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VideoSummaryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            title: 'Offset'
        }
    },
    type: 'object',
    required: ['data', 'count', 'limit', 'offset'],
    title: 'VideosPublic'
} as const;
