// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { IngestCreateIngestJobData, IngestCreateIngestJobResponse, IngestReadIngestJobsData, IngestReadIngestJobsResponse, IngestReadIngestJobData, IngestReadIngestJobResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, MediaReadMediaAssetData, MediaReadMediaAssetResponse, MediaCreateMediaSignedUrlData, MediaCreateMediaSignedUrlResponse, MediaCreateMediaPlaybackUrlResponseData, MediaCreateMediaPlaybackUrlResponseResponse, MediaReadMediaDownloadDescriptorData, MediaReadMediaDownloadDescriptorResponse, MediaProxyMediaAssetData, MediaProxyMediaAssetResponse, PrivateCreateUserData, PrivateCreateUserResponse, SystemReadBilibiliAccessStatusResponse, SystemUpdateBilibiliAccessStatusData, SystemUpdateBilibiliAccessStatusResponse, SystemClearBilibiliAccessStatusResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, VideosReadVideosData, VideosReadVideosResponse, VideosReadVideoData, VideosReadVideoResponse, VideosDeleteVideoData, VideosDeleteVideoResponse, VideosReadVideoAssetsData, VideosReadVideoAssetsResponse, VideosReadVideoCommentsData, VideosReadVideoCommentsResponse, VideosReadVideoCommentImagesData, VideosReadVideoCommentImagesResponse, VideosReadVideoDanmakuData, VideosReadVideoDanmakuResponse, VideosReadVideoSubtitlesData, VideosReadVideoSubtitlesResponse } from './types.gen';

export class IngestService {
    /**
     * Create Ingest Job
     * @param data The data for the request.
     * @param data.requestBody
     * @returns IngestJobPublic Successful Response
     * @throws ApiError
     */
    public static createIngestJob(data: IngestCreateIngestJobData): CancelablePromise<IngestCreateIngestJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ingest/videos',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Ingest Jobs
     * @param data The data for the request.
     * @param data.status
     * @param data.bvid
     * @param data.requestedBy
     * @param data.limit
     * @param data.offset
     * @returns IngestJobsPublic Successful Response
     * @throws ApiError
     */
    public static readIngestJobs(data: IngestReadIngestJobsData = {}): CancelablePromise<IngestReadIngestJobsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ingest/jobs',
            query: {
                status: data.status,
                bvid: data.bvid,
                requested_by: data.requestedBy,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Ingest Job
     * @param data The data for the request.
     * @param data.jobId
     * @returns IngestJobDetail Successful Response
     * @throws ApiError
     */
    public static readIngestJob(data: IngestReadIngestJobData): CancelablePromise<IngestReadIngestJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ingest/jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class MediaService {
    /**
     * Read Media Asset
     * @param data The data for the request.
     * @param data.assetId
     * @returns MediaAssetDetailPublic Successful Response
     * @throws ApiError
     */
    public static readMediaAsset(data: MediaReadMediaAssetData): CancelablePromise<MediaReadMediaAssetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/media/assets/{asset_id}',
            path: {
                asset_id: data.assetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Media Signed Url
     * @param data The data for the request.
     * @param data.assetId
     * @param data.requestBody
     * @returns SignedUrlResponse Successful Response
     * @throws ApiError
     */
    public static createMediaSignedUrl(data: MediaCreateMediaSignedUrlData): CancelablePromise<MediaCreateMediaSignedUrlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/media/assets/{asset_id}/signed-url',
            path: {
                asset_id: data.assetId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Media Playback Url Response
     * @param data The data for the request.
     * @param data.assetId
     * @param data.requestBody
     * @returns SignedUrlResponse Successful Response
     * @throws ApiError
     */
    public static createMediaPlaybackUrlResponse(data: MediaCreateMediaPlaybackUrlResponseData): CancelablePromise<MediaCreateMediaPlaybackUrlResponseResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/media/assets/{asset_id}/playback-url',
            path: {
                asset_id: data.assetId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Media Download Descriptor
     * @param data The data for the request.
     * @param data.assetId
     * @param data.token
     * @returns MediaAssetDownloadDescriptor Successful Response
     * @throws ApiError
     */
    public static readMediaDownloadDescriptor(data: MediaReadMediaDownloadDescriptorData): CancelablePromise<MediaReadMediaDownloadDescriptorResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/media/assets/{asset_id}/download',
            path: {
                asset_id: data.assetId
            },
            query: {
                token: data.token
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Proxy Media Asset
     * @param data The data for the request.
     * @param data.assetId
     * @param data.token
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static proxyMediaAsset(data: MediaProxyMediaAssetData): CancelablePromise<MediaProxyMediaAssetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/media/assets/{asset_id}/playback',
            path: {
                asset_id: data.assetId
            },
            query: {
                token: data.token
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SystemService {
    /**
     * Read Bilibili Access Status
     * @returns BilibiliAccessStatusPublic Successful Response
     * @throws ApiError
     */
    public static readBilibiliAccessStatus(): CancelablePromise<SystemReadBilibiliAccessStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/system/bilibili-access'
        });
    }
    
    /**
     * Update Bilibili Access Status
     * @param data The data for the request.
     * @param data.requestBody
     * @returns BilibiliAccessStatusPublic Successful Response
     * @throws ApiError
     */
    public static updateBilibiliAccessStatus(data: SystemUpdateBilibiliAccessStatusData): CancelablePromise<SystemUpdateBilibiliAccessStatusResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/system/bilibili-access',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Clear Bilibili Access Status
     * @returns BilibiliAccessStatusPublic Successful Response
     * @throws ApiError
     */
    public static clearBilibiliAccessStatus(): CancelablePromise<SystemClearBilibiliAccessStatusResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/system/bilibili-access'
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class VideosService {
    /**
     * Read Videos
     * @param data The data for the request.
     * @param data.q
     * @param data.limit
     * @param data.offset
     * @returns VideosPublic Successful Response
     * @throws ApiError
     */
    public static readVideos(data: VideosReadVideosData = {}): CancelablePromise<VideosReadVideosResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/videos/',
            query: {
                q: data.q,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Video
     * @param data The data for the request.
     * @param data.bvid
     * @returns VideoDetailPublic Successful Response
     * @throws ApiError
     */
    public static readVideo(data: VideosReadVideoData): CancelablePromise<VideosReadVideoResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/videos/{bvid}',
            path: {
                bvid: data.bvid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Video
     * @param data The data for the request.
     * @param data.bvid
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteVideo(data: VideosDeleteVideoData): CancelablePromise<VideosDeleteVideoResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/videos/{bvid}',
            path: {
                bvid: data.bvid
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Video Assets
     * @param data The data for the request.
     * @param data.bvid
     * @param data.assetType
     * @returns VideoAssetsPublic Successful Response
     * @throws ApiError
     */
    public static readVideoAssets(data: VideosReadVideoAssetsData): CancelablePromise<VideosReadVideoAssetsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/videos/{bvid}/assets',
            path: {
                bvid: data.bvid
            },
            query: {
                asset_type: data.assetType
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Video Comments
     * @param data The data for the request.
     * @param data.bvid
     * @param data.root
     * @param data.parent
     * @param data.limit
     * @param data.offset
     * @returns VideoCommentsPublic Successful Response
     * @throws ApiError
     */
    public static readVideoComments(data: VideosReadVideoCommentsData): CancelablePromise<VideosReadVideoCommentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/videos/{bvid}/comments',
            path: {
                bvid: data.bvid
            },
            query: {
                root: data.root,
                parent: data.parent,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Video Comment Images
     * @param data The data for the request.
     * @param data.bvid
     * @param data.rpid
     * @param data.root
     * @param data.parent
     * @param data.storageStatus
     * @param data.limit
     * @param data.offset
     * @returns VideoCommentImagesPublic Successful Response
     * @throws ApiError
     */
    public static readVideoCommentImages(data: VideosReadVideoCommentImagesData): CancelablePromise<VideosReadVideoCommentImagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/videos/{bvid}/comment-images',
            path: {
                bvid: data.bvid
            },
            query: {
                rpid: data.rpid,
                root: data.root,
                parent: data.parent,
                storage_status: data.storageStatus,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Video Danmaku
     * @param data The data for the request.
     * @param data.bvid
     * @param data.cid
     * @param data.source
     * @param data.historyDate
     * @param data.limit
     * @param data.offset
     * @returns VideoDanmakuEntriesPublic Successful Response
     * @throws ApiError
     */
    public static readVideoDanmaku(data: VideosReadVideoDanmakuData): CancelablePromise<VideosReadVideoDanmakuResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/videos/{bvid}/danmaku',
            path: {
                bvid: data.bvid
            },
            query: {
                cid: data.cid,
                source: data.source,
                history_date: data.historyDate,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Video Subtitles
     * @param data The data for the request.
     * @param data.bvid
     * @param data.cid
     * @param data.lang
     * @param data.limit
     * @param data.offset
     * @returns VideoSubtitlesPublic Successful Response
     * @throws ApiError
     */
    public static readVideoSubtitles(data: VideosReadVideoSubtitlesData): CancelablePromise<VideosReadVideoSubtitlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/videos/{bvid}/subtitles',
            path: {
                bvid: data.bvid
            },
            query: {
                cid: data.cid,
                lang: data.lang,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}