// This file is auto-generated by @hey-api/openapi-ts

export type AuxiliarySourceJobPublic = {
    job_id: string;
    status: string;
    phase?: (string | null);
    crawled_at?: (string | null);
};

export type BilibiliAccessStatusPublic = {
    metadata_cookie_configured: boolean;
    download_auth_configured: boolean;
    has_database_override: boolean;
    effective_cookie_source: string;
    cookie_header_summary?: (string | null);
    netscape_cookie_summary?: (string | null);
    download_user_agent_summary?: (string | null);
    download_user_agent_configured?: boolean;
    yt_dlp_cookies_file_configured: boolean;
    yt_dlp_cookies_from_browser_configured: boolean;
    yt_dlp_impersonate_configured?: boolean;
    database_cookie_updated_by?: (string | null);
    database_cookie_updated_at?: (string | null);
    warnings?: Array<(string)>;
};

export type BilibiliAccessUpdate = {
    netscape_cookies: string;
    download_user_agent?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IngestJobDetail = {
    job_id: string;
    bvid?: (string | null);
    status: string;
    phase?: (string | null);
    requested_by?: (string | null);
    options?: {
        [key: string]: unknown;
    };
    progress?: {
        [key: string]: unknown;
    };
    error?: (JobErrorPublic | null);
    created_at: string;
    started_at?: (string | null);
    finished_at?: (string | null);
};

export type IngestJobPublic = {
    job_id: string;
    bvid?: (string | null);
    status: string;
    phase?: (string | null);
};

export type IngestJobsPublic = {
    data: Array<IngestJobSummaryPublic>;
    count: number;
    limit: number;
    offset: number;
};

export type IngestJobSummaryPublic = {
    job_id: string;
    bvid?: (string | null);
    status: string;
    phase?: (string | null);
    requested_by?: (string | null);
    error?: (JobErrorPublic | null);
    created_at: string;
    started_at?: (string | null);
    finished_at?: (string | null);
};

export type IngestVideoOptions = {
    download_video?: boolean;
    max_height?: (number | null);
    store_source_archive?: boolean;
    create_normalized_mp4?: boolean;
    create_hls?: boolean;
    fetch_comments?: boolean;
    fetch_danmaku?: boolean;
    fetch_subtitles?: boolean;
    transcribe_subtitles?: boolean;
    force_refresh?: boolean;
};

export type IngestVideoRequest = {
    input: string;
    options?: IngestVideoOptions;
};

export type JobErrorPublic = {
    code?: (string | null);
    message?: (string | null);
};

export type MediaAssetDetailPublic = {
    asset_id: string;
    asset_type: string;
    variant?: (string | null);
    status: string;
    cid?: (number | null);
    filename?: (string | null);
    content_type?: (string | null);
    size_bytes?: (number | null);
    sha256?: (string | null);
    container_format?: (string | null);
    video_codec?: (string | null);
    audio_codec?: (string | null);
    width?: (number | null);
    height?: (number | null);
    duration_seconds?: (number | null);
    created_at: string;
    ready_at?: (string | null);
    bvid: string;
    s3_bucket?: (string | null);
    s3_key?: (string | null);
};

export type MediaAssetDownloadDescriptor = {
    asset_id: string;
    bvid: string;
    s3_bucket?: (string | null);
    s3_key?: (string | null);
    filename?: (string | null);
    content_type?: (string | null);
    expires_at: string;
};

export type MediaAssetPublic = {
    asset_id: string;
    asset_type: string;
    variant?: (string | null);
    status: string;
    cid?: (number | null);
    filename?: (string | null);
    content_type?: (string | null);
    size_bytes?: (number | null);
    sha256?: (string | null);
    container_format?: (string | null);
    video_codec?: (string | null);
    audio_codec?: (string | null);
    width?: (number | null);
    height?: (number | null);
    duration_seconds?: (number | null);
    created_at: string;
    ready_at?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SignedUrlRequest = {
    expires_in?: number;
};

export type SignedUrlResponse = {
    url: string;
    expires_in: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VideoAssetsPublic = {
    bvid: string;
    assets: Array<MediaAssetPublic>;
};

export type VideoCommentContextPublic = {
    rpid: number;
    oid?: (number | null);
    mid?: (number | null);
    uname?: (string | null);
    root?: (number | null);
    parent?: (number | null);
    message?: (string | null);
    like_count?: (number | null);
    reply_count?: (number | null);
    ctime?: (string | null);
};

export type VideoCommentImageEntryPublic = {
    source_url?: (string | null);
    width?: (number | null);
    height?: (number | null);
    asset_id?: (string | null);
    storage_status: string;
    error_message?: (string | null);
    asset?: (MediaAssetPublic | null);
    image_id: string;
    ordinal: number;
    crawled_at: string;
    comment: VideoCommentContextPublic;
};

export type VideoCommentImagePublic = {
    source_url?: (string | null);
    width?: (number | null);
    height?: (number | null);
    asset_id?: (string | null);
    storage_status: string;
    error_message?: (string | null);
    asset?: (MediaAssetPublic | null);
};

export type VideoCommentImagesPublic = {
    bvid: string;
    count: number;
    limit: number;
    offset: number;
    completeness?: (VideoCommentsCompletenessPublic | null);
    images: Array<VideoCommentImageEntryPublic>;
};

export type VideoCommentPublic = {
    rpid: number;
    oid?: (number | null);
    mid?: (number | null);
    uname?: (string | null);
    root?: (number | null);
    parent?: (number | null);
    message?: (string | null);
    like_count?: (number | null);
    reply_count?: (number | null);
    ctime?: (string | null);
    images?: Array<VideoCommentImagePublic>;
};

export type VideoCommentsCompletenessPublic = {
    partial?: (boolean | null);
    expected_count?: (number | null);
    fetched_count?: (number | null);
    stored_count?: (number | null);
    fallback_used?: (boolean | null);
    image_count?: (number | null);
    stored_image_count?: (number | null);
    failed_image_count?: (number | null);
    skipped_image_count?: (number | null);
    source_job: AuxiliarySourceJobPublic;
};

export type VideoCommentsPublic = {
    bvid: string;
    count: number;
    thread_count?: (number | null);
    limit: number;
    offset: number;
    completeness?: (VideoCommentsCompletenessPublic | null);
    comments: Array<VideoCommentPublic>;
};

export type VideoDanmakuCompletenessPublic = {
    partial?: (boolean | null);
    stored_count?: (number | null);
    duplicate_count?: (number | null);
    cid_count?: (number | null);
    filled_cid_count?: (number | null);
    crawl_source?: (string | null);
    history_used?: (boolean | null);
    snapshot_used?: (boolean | null);
    indexed_month_count?: (number | null);
    expected_days_count?: (number | null);
    fetched_days_count?: (number | null);
    pages?: Array<VideoDanmakuPageCoveragePublic>;
    source_job: AuxiliarySourceJobPublic;
};

export type VideoDanmakuEntriesPublic = {
    bvid: string;
    count: number;
    limit: number;
    offset: number;
    completeness?: (VideoDanmakuCompletenessPublic | null);
    danmaku: Array<VideoDanmakuEntryPublic>;
};

export type VideoDanmakuEntryPublic = {
    danmaku_id?: (number | null);
    cid: number;
    time_offset_seconds?: (number | null);
    mode?: (number | null);
    font_size?: (number | null);
    color?: (number | null);
    content?: (string | null);
    sent_at?: (string | null);
    source: string;
    history_date?: (string | null);
};

export type VideoDanmakuPageCoveragePublic = {
    cid: number;
    count?: (number | null);
    source?: (string | null);
    history_used?: (boolean | null);
    snapshot_used?: (boolean | null);
    indexed_month_count?: (number | null);
    expected_days_count?: (number | null);
    fetched_days_count?: (number | null);
    partial?: (boolean | null);
};

export type VideoDetailPublic = {
    bvid: string;
    aid?: (number | null);
    title: string;
    owner_mid?: (number | null);
    owner_name?: (string | null);
    duration_seconds?: (number | null);
    pubdate?: (string | null);
    category?: (string | null);
    cover_url?: (string | null);
    tags?: Array<(string)>;
    takedown_status: string;
    last_crawled_at?: (string | null);
    description?: (string | null);
    stat?: {
        [key: string]: unknown;
    };
};

export type VideosPublic = {
    data: Array<VideoSummaryPublic>;
    count: number;
    limit: number;
    offset: number;
};

export type VideoSubtitlePublic = {
    subtitle_id: string;
    cid?: (number | null);
    lang?: (string | null);
    source?: (string | null);
    content?: (string | null);
    asset_id?: (string | null);
    crawled_at: string;
};

export type VideoSubtitlesCompletenessPublic = {
    partial?: (boolean | null);
    stored_count?: (number | null);
    cid_count?: (number | null);
    languages?: Array<(string)>;
    source_job: AuxiliarySourceJobPublic;
};

export type VideoSubtitlesPublic = {
    bvid: string;
    count: number;
    limit: number;
    offset: number;
    completeness?: (VideoSubtitlesCompletenessPublic | null);
    subtitles: Array<VideoSubtitlePublic>;
};

export type VideoSummaryPublic = {
    bvid: string;
    aid?: (number | null);
    title: string;
    owner_mid?: (number | null);
    owner_name?: (string | null);
    duration_seconds?: (number | null);
    pubdate?: (string | null);
    category?: (string | null);
    cover_url?: (string | null);
    tags?: Array<(string)>;
    takedown_status: string;
    last_crawled_at?: (string | null);
};

export type IngestCreateIngestJobData = {
    requestBody: IngestVideoRequest;
};

export type IngestCreateIngestJobResponse = (IngestJobPublic);

export type IngestReadIngestJobsData = {
    bvid?: (string | null);
    limit?: number;
    offset?: number;
    requestedBy?: (string | null);
    status?: (string | null);
};

export type IngestReadIngestJobsResponse = (IngestJobsPublic);

export type IngestReadIngestJobData = {
    jobId: string;
};

export type IngestReadIngestJobResponse = (IngestJobDetail);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaReadMediaAssetData = {
    assetId: string;
};

export type MediaReadMediaAssetResponse = (MediaAssetDetailPublic);

export type MediaCreateMediaSignedUrlData = {
    assetId: string;
    requestBody: SignedUrlRequest;
};

export type MediaCreateMediaSignedUrlResponse = (SignedUrlResponse);

export type MediaCreateMediaPlaybackUrlResponseData = {
    assetId: string;
    requestBody: SignedUrlRequest;
};

export type MediaCreateMediaPlaybackUrlResponseResponse = (SignedUrlResponse);

export type MediaReadMediaDownloadDescriptorData = {
    assetId: string;
    token: string;
};

export type MediaReadMediaDownloadDescriptorResponse = (MediaAssetDownloadDescriptor);

export type MediaProxyMediaAssetData = {
    assetId: string;
    token: string;
};

export type MediaProxyMediaAssetResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SystemReadBilibiliAccessStatusResponse = (BilibiliAccessStatusPublic);

export type SystemUpdateBilibiliAccessStatusData = {
    requestBody: BilibiliAccessUpdate;
};

export type SystemUpdateBilibiliAccessStatusResponse = (BilibiliAccessStatusPublic);

export type SystemClearBilibiliAccessStatusResponse = (BilibiliAccessStatusPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type VideosReadVideosData = {
    limit?: number;
    offset?: number;
    q?: (string | null);
};

export type VideosReadVideosResponse = (VideosPublic);

export type VideosReadVideoData = {
    bvid: string;
};

export type VideosReadVideoResponse = (VideoDetailPublic);

export type VideosDeleteVideoData = {
    bvid: string;
};

export type VideosDeleteVideoResponse = (Message);

export type VideosReadVideoAssetsData = {
    assetType?: (string | null);
    bvid: string;
};

export type VideosReadVideoAssetsResponse = (VideoAssetsPublic);

export type VideosReadVideoCommentsData = {
    bvid: string;
    limit?: number;
    offset?: number;
    parent?: (number | null);
    root?: (number | null);
};

export type VideosReadVideoCommentsResponse = (VideoCommentsPublic);

export type VideosReadVideoCommentImagesData = {
    bvid: string;
    limit?: number;
    offset?: number;
    parent?: (number | null);
    root?: (number | null);
    rpid?: (number | null);
    storageStatus?: (string | null);
};

export type VideosReadVideoCommentImagesResponse = (VideoCommentImagesPublic);

export type VideosReadVideoDanmakuData = {
    bvid: string;
    cid?: (number | null);
    historyDate?: (string | null);
    limit?: number;
    offset?: number;
    source?: (string | null);
};

export type VideosReadVideoDanmakuResponse = (VideoDanmakuEntriesPublic);

export type VideosReadVideoSubtitlesData = {
    bvid: string;
    cid?: (number | null);
    lang?: (string | null);
    limit?: number;
    offset?: number;
};

export type VideosReadVideoSubtitlesResponse = (VideoSubtitlesPublic);
