"""initialize current schema

Revision ID: 20260420_01
Revises:
Create Date: 2026-04-20 20:51:59.552508

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "20260420_01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "resource_type",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "resource_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor"), "audit_events", ["actor"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_resource_id"),
        "audit_events",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_resource_type"),
        "audit_events",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("input_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "normalized_bvid",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=True,
        ),
        sa.Column(
            "requested_by",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "phase", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("progress", sa.JSON(), nullable=False),
        sa.Column(
            "idempotency_key",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column(
            "error_code",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_ingest_jobs_created_at"), "ingest_jobs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_ingest_jobs_normalized_bvid"),
        "ingest_jobs",
        ["normalized_bvid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_jobs_requested_by"),
        "ingest_jobs",
        ["requested_by"],
        unique=False,
    )
    op.create_index(op.f("ix_ingest_jobs_status"), "ingest_jobs", ["status"], unique=False)
    op.create_table(
        "uploaders",
        sa.Column("mid", sa.BigInteger(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "avatar_url",
            sqlmodel.sql.sqltypes.AutoString(length=1024),
            nullable=True,
        ),
        sa.Column(
            "avatar_s3_key",
            sqlmodel.sql.sqltypes.AutoString(length=1024),
            nullable=True,
        ),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("mid"),
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('videos',
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('aid', sa.BigInteger(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('pubdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_mid', sa.BigInteger(), nullable=True),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('cover_s3_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('stat', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('takedown_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_mid'], ['uploaders.mid'], ),
    sa.PrimaryKeyConstraint('bvid')
    )
    op.create_index(op.f('ix_videos_aid'), 'videos', ['aid'], unique=True)
    op.create_index(op.f('ix_videos_owner_mid'), 'videos', ['owner_mid'], unique=False)
    op.create_index(op.f('ix_videos_pubdate'), 'videos', ['pubdate'], unique=False)
    op.create_index(op.f('ix_videos_takedown_status'), 'videos', ['takedown_status'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cid', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('s3_bucket', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('s3_region', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('storage_class', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('original_url_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('container_format', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('video_codec', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('audio_codec', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('bitrate', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["bvid"], ["videos.bvid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["job_id"], ["ingest_jobs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f('ix_media_assets_asset_type'), 'media_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_media_assets_bvid'), 'media_assets', ['bvid'], unique=False)
    op.create_index(op.f('ix_media_assets_cid'), 'media_assets', ['cid'], unique=False)
    op.create_index(op.f('ix_media_assets_status'), 'media_assets', ['status'], unique=False)
    op.create_index(
        "ix_media_assets_bvid_asset_type",
        "media_assets",
        ["bvid", "asset_type"],
        unique=False,
    )
    op.create_index(
        "ix_media_assets_ready_asset_by_sha256",
        "media_assets",
        ["sha256", "asset_type"],
        unique=True,
        postgresql_where=sa.text("sha256 IS NOT NULL AND status IN ('uploaded', 'ready')"),
    )
    op.create_table('video_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rpid', sa.BigInteger(), nullable=False),
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('oid', sa.BigInteger(), nullable=True),
    sa.Column('mid', sa.BigInteger(), nullable=True),
    sa.Column('uname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('root', sa.BigInteger(), nullable=True),
    sa.Column('parent', sa.BigInteger(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('reply_count', sa.BigInteger(), nullable=True),
    sa.Column('ctime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bvid"], ["videos.bvid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bvid', 'rpid', name='uq_video_comments_bvid_rpid')
    )
    op.create_index(op.f('ix_video_comments_bvid'), 'video_comments', ['bvid'], unique=False)
    op.create_index(op.f('ix_video_comments_ctime'), 'video_comments', ['ctime'], unique=False)
    op.create_index(op.f('ix_video_comments_mid'), 'video_comments', ['mid'], unique=False)
    op.create_index(
        "ix_video_comments_bvid_ctime",
        "video_comments",
        ["bvid", "ctime"],
        unique=False,
    )
    op.create_table('video_danmaku',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('danmaku_id', sa.BigInteger(), nullable=True),
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cid', sa.BigInteger(), nullable=False),
    sa.Column('time_offset_seconds', sa.Float(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('history_date', sa.Date(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bvid"], ["videos.bvid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bvid', 'cid', 'danmaku_id', name='uq_video_danmaku_bvid_cid_danmaku_id')
    )
    op.create_index(op.f('ix_video_danmaku_bvid'), 'video_danmaku', ['bvid'], unique=False)
    op.create_index(op.f('ix_video_danmaku_cid'), 'video_danmaku', ['cid'], unique=False)
    op.create_index(op.f('ix_video_danmaku_danmaku_id'), 'video_danmaku', ['danmaku_id'], unique=False)
    op.create_index(op.f('ix_video_danmaku_history_date'), 'video_danmaku', ['history_date'], unique=False)
    op.create_index(op.f('ix_video_danmaku_source'), 'video_danmaku', ['source'], unique=False)
    op.create_index(
        "ix_video_danmaku_cid_time_offset_seconds",
        "video_danmaku",
        ["cid", "time_offset_seconds"],
        unique=False,
    )
    op.create_table('video_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('aid', sa.BigInteger(), nullable=True),
    sa.Column('cid', sa.BigInteger(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('part_title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bvid"], ["videos.bvid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bvid', 'cid', name='uq_video_pages_bvid_cid'),
        sa.UniqueConstraint('bvid', 'page_no', name='uq_video_pages_bvid_page_no')
    )
    op.create_index(op.f('ix_video_pages_bvid'), 'video_pages', ['bvid'], unique=False)
    op.create_index(op.f('ix_video_pages_cid'), 'video_pages', ['cid'], unique=False)
    op.create_index(op.f('ix_video_pages_page_no'), 'video_pages', ['page_no'], unique=False)
    op.create_table('video_stat_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('coin_count', sa.BigInteger(), nullable=True),
    sa.Column('favorite_count', sa.BigInteger(), nullable=True),
    sa.Column('reply_count', sa.BigInteger(), nullable=True),
    sa.Column('share_count', sa.BigInteger(), nullable=True),
    sa.Column('danmaku_count', sa.BigInteger(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bvid"], ["videos.bvid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_stat_snapshots_bvid'), 'video_stat_snapshots', ['bvid'], unique=False)
    op.create_index(op.f('ix_video_stat_snapshots_crawled_at'), 'video_stat_snapshots', ['crawled_at'], unique=False)
    op.create_index(
        "ix_video_stat_snapshots_bvid_crawled_at",
        "video_stat_snapshots",
        ["bvid", "crawled_at"],
        unique=False,
    )
    op.create_table('video_comment_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('rpid', sa.BigInteger(), nullable=False),
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('storage_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["media_assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["bvid"], ["videos.bvid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["video_comments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('comment_id', 'ordinal', name='uq_video_comment_images_comment_id_ordinal')
    )
    op.create_index(op.f('ix_video_comment_images_bvid'), 'video_comment_images', ['bvid'], unique=False)
    op.create_index(op.f('ix_video_comment_images_comment_id'), 'video_comment_images', ['comment_id'], unique=False)
    op.create_index(op.f('ix_video_comment_images_crawled_at'), 'video_comment_images', ['crawled_at'], unique=False)
    op.create_index(op.f('ix_video_comment_images_rpid'), 'video_comment_images', ['rpid'], unique=False)
    op.create_table('video_subtitles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bvid', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cid', sa.BigInteger(), nullable=True),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["media_assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["bvid"], ["videos.bvid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_subtitles_bvid'), 'video_subtitles', ['bvid'], unique=False)
    op.create_index(op.f('ix_video_subtitles_cid'), 'video_subtitles', ['cid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_subtitles_cid'), table_name='video_subtitles')
    op.drop_index(op.f('ix_video_subtitles_bvid'), table_name='video_subtitles')
    op.drop_table('video_subtitles')
    op.drop_index(op.f('ix_video_comment_images_rpid'), table_name='video_comment_images')
    op.drop_index(op.f('ix_video_comment_images_crawled_at'), table_name='video_comment_images')
    op.drop_index(op.f('ix_video_comment_images_comment_id'), table_name='video_comment_images')
    op.drop_index(op.f('ix_video_comment_images_bvid'), table_name='video_comment_images')
    op.drop_table('video_comment_images')
    op.drop_index(
        "ix_video_stat_snapshots_bvid_crawled_at",
        table_name="video_stat_snapshots",
    )
    op.drop_index(op.f('ix_video_stat_snapshots_crawled_at'), table_name='video_stat_snapshots')
    op.drop_index(op.f('ix_video_stat_snapshots_bvid'), table_name='video_stat_snapshots')
    op.drop_table('video_stat_snapshots')
    op.drop_index(op.f('ix_video_pages_page_no'), table_name='video_pages')
    op.drop_index(op.f('ix_video_pages_cid'), table_name='video_pages')
    op.drop_index(op.f('ix_video_pages_bvid'), table_name='video_pages')
    op.drop_table('video_pages')
    op.drop_index(op.f('ix_video_danmaku_source'), table_name='video_danmaku')
    op.drop_index(op.f('ix_video_danmaku_history_date'), table_name='video_danmaku')
    op.drop_index(op.f('ix_video_danmaku_danmaku_id'), table_name='video_danmaku')
    op.drop_index(op.f('ix_video_danmaku_cid'), table_name='video_danmaku')
    op.drop_index(op.f('ix_video_danmaku_bvid'), table_name='video_danmaku')
    op.drop_index(
        "ix_video_danmaku_cid_time_offset_seconds",
        table_name="video_danmaku",
    )
    op.drop_table('video_danmaku')
    op.drop_index("ix_video_comments_bvid_ctime", table_name="video_comments")
    op.drop_index(op.f('ix_video_comments_mid'), table_name='video_comments')
    op.drop_index(op.f('ix_video_comments_ctime'), table_name='video_comments')
    op.drop_index(op.f('ix_video_comments_bvid'), table_name='video_comments')
    op.drop_table('video_comments')
    op.drop_index(
        "ix_media_assets_ready_asset_by_sha256",
        table_name="media_assets",
        postgresql_where=sa.text("sha256 IS NOT NULL AND status IN ('uploaded', 'ready')"),
    )
    op.drop_index("ix_media_assets_bvid_asset_type", table_name="media_assets")
    op.drop_index(op.f('ix_media_assets_status'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_cid'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_bvid'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_asset_type'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_videos_takedown_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_pubdate'), table_name='videos')
    op.drop_index(op.f('ix_videos_owner_mid'), table_name='videos')
    op.drop_index(op.f('ix_videos_aid'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('uploaders')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_requested_by'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_normalized_bvid'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_created_at'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
